package com.steveluland.gamecast.characterdetail.model

data class CharacterDetail(
    private val aliases: String = "",
    private val api_detail_url: String = "",
    private val birthday: String = "",
    private val concepts: String = "",
    private val date_added: String = "",
    private val date_last_updated: String = "",
    private val deck: String = "",
    private val description: String = "",
    private val enemies: String = "",
    private val first_appeared_in_game: String = "",
    private val franchises: String = "",
    private val friends: String = "",
    private val games: String = "",
    private val gender: String = "",
    private val guid: String = "",
    private val id: String = "",
    private val image: String = "",
    private val image_tags: String = "",
    private val last_name: String = "",
    private val locations: String = "",
    private val name: String = "",
    private val objects: String = "",
    private val people: String = "",
    private val real_name: String = "",
    private val site_detail_url: String = "",
)
