package com.steveluland.gamecast.characterdetail.model

data class CharacterDetail(
//    val aliases: String = "",
//    val api_detail_url: String = "",
//    val birthday: String = "",
//    val concepts: String = "",
//    val date_added: String = "",
//    val date_last_updated: String = "",
//    val deck: String = "",
    val description: String = "",
//    val enemies: String = "",
//    val first_appeared_in_game: String = "",
//    val franchises: String = "",
//    val friends: String = "",
//    val games: String = "",
//    val gender: String = "",
//    val guid: String = "",
//    val id: String = "",
//    val image: String = "",
//    val image_tags: String = "",
//    val last_name: String = "",
//    val locations: String = "",
    val name: String = "",
//    val objects: String = "",
//    val people: String = "",
//    val real_name: String = "",
//    val site_detail_url: String = "",
)
